version: "3.4"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.12
    ports:
      - "${EXPOSED_MQTT_PORT}:1883"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  postgres:
    image: postgres:13.4
    ports:
      - "${EXPOSED_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
  datacollector:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: ["./mvnw -B compile quarkus:dev"]
    depends_on:
      - postgres
    environment:
      MQTT_URL: ${MQTT_URL}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_FLIGHTDATA_TOPIC: ${MQTT_FLIGHTDATA_TOPIC}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_HTTP_HOST: 0.0.0.0
    ports:
      - "${EXPOSED_DATACOLLECTOR_REST_PORT}:8080"
      - "${EXPOSED_DATACOLLECTOR_WEBSOCKET_PORT}:8081"
